export const ErrorCodes = {
  Organizations: {
    LAST_OWNER: 'LAST_OWNER',
    INVALID_INVITATION: 'INVALID_INVITATION',
  },
  Access: {
    MISSING_PERMISSION: 'MISSING_PERMISSION',
    OWNER_ONLY: 'OWNER_ONLY',
    RANK_TOO_LOW: 'RANK_TOO_LOW',
    GRANT_EXCEEDS_OWN: 'GRANT_EXCEEDS_OWN',
    SELF_MODIFICATION: 'SELF_MODIFICATION',
    IMMUTABLE_ROLE: 'IMMUTABLE_ROLE',
  },
  Integrations: {
    COMPOSIO_NOT_CONFIGURED: 'COMPOSIO_NOT_CONFIGURED',
    CONNECTION_NOT_ACTIVE: 'CONNECTION_NOT_ACTIVE',
    PROVIDER_ERROR: 'PROVIDER_ERROR',
    NOTION_PAGE_NOT_EDITABLE: 'NOTION_PAGE_NOT_EDITABLE',
  },
};
