export const ErrorCodes = {
  Organizations: {
    LAST_OWNER: 'LAST_OWNER',
    INVALID_INVITATION: 'INVALID_INVITATION',
  },
  Integrations: {
    COMPOSIO_NOT_CONFIGURED: 'COMPOSIO_NOT_CONFIGURED',
    CONNECTION_NOT_ACTIVE: 'CONNECTION_NOT_ACTIVE',
    PROVIDER_ERROR: 'PROVIDER_ERROR',
  },
};
